#pragma once
#include "SEShaderElements.h"

//class SEResourceElement
//{
//
//};
namespace Charalotte
{
	struct FResourceElement
	{
		int DsDsvOffest = 0;
		int DsRtvOffest = 0;
		int RtDsvOffest = 0;
		int RtRtvOffest = 0;
	};
	enum class E_RESOURCE_TYPE
	{
		RESOURCE_DEP,
		RESOURCE_SHADER,
		RESOURCE_RT
	};

	enum class E_RESOURCE_STATE
	{
		RESOURCE_STATE_COMMON = 0,
		RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER = 0x1,
		RESOURCE_STATE_INDEX_BUFFER = 0x2,
		RESOURCE_STATE_RENDER_TARGET = 0x4,
		RESOURCE_STATE_UNORDERED_ACCESS = 0x8,
		RESOURCE_STATE_DEPTH_WRITE = 0x10,
		RESOURCE_STATE_DEPTH_READ = 0x20,
		RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE = 0x40,
		RESOURCE_STATE_PIXEL_SHADER_RESOURCE = 0x80,
		RESOURCE_STATE_STREAM_OUT = 0x100,
		RESOURCE_STATE_INDIRECT_ARGUMENT = 0x200,
		RESOURCE_STATE_COPY_DEST = 0x400,
		RESOURCE_STATE_COPY_SOURCE = 0x800,
		RESOURCE_STATE_RESOLVE_DEST = 0x1000,
		RESOURCE_STATE_RESOLVE_SOURCE = 0x2000,
		RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE = 0x400000,
		RESOURCE_STATE_SHADING_RATE_SOURCE = 0x1000000,
		RESOURCE_STATE_GENERIC_READ = (((((0x1 | 0x2) | 0x40) | 0x80) | 0x200) | 0x800),
		RESOURCE_STATE_PRESENT = 0,
		RESOURCE_STATE_PREDICATION = 0x200,
		RESOURCE_STATE_VIDEO_DECODE_READ = 0x10000,
		RESOURCE_STATE_VIDEO_DECODE_WRITE = 0x20000,
		RESOURCE_STATE_VIDEO_PROCESS_READ = 0x40000,
		RESOURCE_STATE_VIDEO_PROCESS_WRITE = 0x80000,
		RESOURCE_STATE_VIDEO_ENCODE_READ = 0x200000,
		RESOURCE_STATE_VIDEO_ENCODE_WRITE = 0x800000
	};

	struct FResourceAttributes
	{
		int RtO = 0;
		int SrO = 0;
		int DsO = 0;
		E_GRAPHIC_FORMAT Format;
		unsigned int Width = 0;
		unsigned int Height = 0;
		E_RESOURCE_TYPE ResourceType;
	};

	
}